구글, 카카오 소셜 로그인 연결
Parrotalk/Parrotalk_BE pull request #1
Opened 2024-11-30 13:57 UTC by KimGyeongLock

## 📌 개요 
  - 구글, 카카오 OAuth2 JWT 로그인 연결
 ## 💻 작업사항 
  - 구글, 카카오 OAuth2 로그인을 JWT 방식으로 연결
  - Access token의 경우 클라이언트에 header로 반환 -> front에서 로컬 스토리지에 저장
  - Refresh token의 경우 http only 쿠키로 저장 & Redis에 저장
  - MySQL 로컬로 연결하여 DB에 저장
  
 ## 📊 테스트 결과 
  <img width="1023" alt="image" src="https://github.com/user-attachments/assets/e53fb26b-8b9e-47a8-91b9-539a40aadee1">

2024-11-30 14:47 UTC, Austin-Choi commented on src/main/resources/application.yml
> +            redirect-uri: http://localhost:8080/login/oauth2/code/google
redirect-uri 앞에 도메인부분도 환경변수로 빼는 게 좋을 것 같습니다.

2024-11-30 14:47 UTC, Austin-Choi commented on src/main/java/com/be/parrotalk/login/domain/ProviderType.java
> +public enum ProviderType {
enum 클래스는 domain보다는 utility이나 util 분류에 적합하다고 생각합니다,,

2024-11-30 14:47 UTC, Austin-Choi commented on src/main/java/com/be/parrotalk/login/controller/AuthController.java
> +    public ResponseEntity<Void> refreshToken(HttpServletResponse response, @RequestBody TokenRefreshRequest request) {
RefreshToken은 body 보다는 Cookie로 관리하는 방법이 Best Practice라고 알고 있습니다. body에 넣어서 전송하게 되면 XSS 공격에 약하고 보통 유효기간이 짧은 access token은 탈취되어도 refresh token만 안전하다면 괜찮습니다.
XSS 공격은 JS 변조로 이루어지기 때문에 refresh token은 cookie에 담는 게 좋다고 생각합니다. Cookie는 JS로 접근할 수 없기 때문에 XSS에 강하고 CSRF 공격에 취약하지만 CSRF는 쿠기의 SameSite 속성을 설정함으로써 보완이 가능합니다. Cookie 방식은 어떻게 생각하시나요?

2024-11-30 14:47 UTC, Austin-Choi commented on src/main/java/com/be/parrotalk/login/security/JwtAuthenticationFilter.java
> +                PrintWriter writer = response.getWriter();
printwriter를 써서 응답을 작성하기보다는 적절한 에러를 throw 하는 방법은 어떻게 생각하세요?

2024-11-30 14:51 UTC, Austin-Choi commented on src/main/java/com/be/parrotalk/login/dto/OAuth2Response.java
> +    public OAuth2Response(Map<String, Object> attributes) {
물론 현재 저희는 구글이랑 카카오 두 가지 로그인 방법밖에 쓰지 않지만 추후 확장성과 반복되는 코드 제거를 위해 전략 패턴을 활용해 보는 건 어떨까요?

2024-12-01 11:48 UTC, Austin-Choi requested changes

2024-12-01 11:48 UTC, Austin-Choi commented on src/main/resources/application.yml
> +            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
이 redirect-uri 부분도 환경변수로 따로 관리하면 좋을 것 같습니다.

2024-12-04 08:05 UTC, KimGyeongLock commented on src/main/resources/application.yml
> +            redirect-uri: http://localhost:8080/login/oauth2/code/google
좋은 것 같습니다!

2024-12-04 08:05 UTC, KimGyeongLock commented on src/main/java/com/be/parrotalk/login/domain/ProviderType.java
> +public enum ProviderType {
좋은 것 같습니다!

2024-12-04 08:06 UTC, KimGyeongLock commented on src/main/java/com/be/parrotalk/login/controller/AuthController.java
> +    public ResponseEntity<Void> refreshToken(HttpServletResponse response, @RequestBody TokenRefreshRequest request) {
간과한 부분인 것 같네요! 수정하겠습니다!

2024-12-04 08:06 UTC, KimGyeongLock commented on src/main/java/com/be/parrotalk/login/security/JwtAuthenticationFilter.java
> +                PrintWriter writer = response.getWriter();
좋은 것 같습니다!

2024-12-04 08:06 UTC, KimGyeongLock commented on src/main/java/com/be/parrotalk/login/dto/OAuth2Response.java
> +    public OAuth2Response(Map<String, Object> attributes) {
좋은 것 같습니다!

2024-12-04 08:16 UTC, closed without merging